### ISSUE TITLE
Error con las migraciones

### ISSUE THREAD

**Issue by cdvv7788** [sebastian-code/django_cali#14]
Cuando intento migrar me aparece un error: django.db.utils.ProgrammingError: relation "auth_group" does not exist.

Dado que esto está relacionado con el modelo de usuarios, antes de proceder con esto sería relevante definir si se va a utilizar alguna app externa para ello. También es recomendable usar una app "users" (en este caso puede ser accounts, pero no se si el nombre pueda generar conflictos despues) que contenga un modelo abstracto de los usuarios, así esté vacio. Esto permite tener la misma funcionalidad que se tiene por defecto pero con la posibilidad de añadir campos facilmente a futuro.

**Comment by sebastian-code** [comment]
para poner en operación de pruebas tienes que crear un archivo "portal/settings/local.env" (el cual no respalda porque lo tengo incluido en mi .gitignore) en el debes apuntar  en la carpeta debes correr el comando migrate, y luego createsuperuser, una vez

**Comment by cdvv7788** [comment]
El repositorio debería tener todo lo que se requiera para crear una instancia local rapidamente.
De todos modos intenté implementar los cambios y tampoco funciona. Sigue diciendo que una relación no existe.
Si ya existe un settings para development, cual es la ventaja de usar un archivo adicional?

**Comment by sebastian-code** [comment]
Que no incluyas las configuraciones de contraseñas (la de encripción de django o los datos de conexión de tu base de datos) o ninguna otro tipo de informacion clave que debe ir en tu configuración de despliegue, en el repositorio publico.

**Comment by cdvv7788** [comment]
Ya vi el settings, lo que hace es cargar lo de ese archivo en las variables de entorno. Aunque no considero que la información para una instancia de dev deba tener toda esta seguridad (Los settings de producción siguen requiriendolo) ya tiene sentido por qué está estructurado así. Voy a revertir los cambios a los settings entonces.

**Comment by sebastian-code** [comment]
Estaba revisando lo que mencionabas sobre el error en las migraciones, y por alguna razón esta relacionado con las migraciones en postgres, una vez que incorporas la configuración de psycopg2, arroja un error con auth__tools, en la pagina de la plantilla Edge hay un issue relacionado con exactamente eso, aquí encuentras una discusión y una forma de solucionarlo https://github.com/arocks/edge/issues/35

**Comment by cdvv7788** [comment]
Gracias!. Por detalles como este es que es preferible usar el mismo motor en dev y en producción.

**Comment by sebastian-code** [comment]
Estaba revisando, y veo que hay un problema al momento de aplicar la migración que se crea después de agregar el manager al modelo, no logro entender que pasa en trasfondo.

**Comment by sebastian-code** [comment]
Revisando el modelo, el error estaba en un cambio que incorpore, tratando de definir que se aplicara por defecto que el autor del articulo seria el usuario en ese momento registrado, sobre todo porque mi deseo era usar un formulario externo para que el usuario no necesitara acceso al portal administrativo, y como lo había diseñado originalmente dibujaba un campo en el formulario que mostraba todos los usuarios.

Quitada la opción las migraciones corren sin problemas.

**Comment by cdvv7788** [comment]
Creo que el problema está en que el usuario está definido en la app auth-tools, por lo que se pierde algo de control (flexibilidad) sobre este modelo.

**Comment by sebastian-code** [comment]
Tienes alguna sugerencia sobre como manejarlo? No se me ocurre nada para hacerlo funcional y conservar la característica.

**Comment by cdvv7788** [comment]
La razón para la cual usar esta app es para usar email en lugar de username? Hay otra razón diferente a esta?

**Comment by sebastian-code** [comment]
No que sepa, realmente es parte de la estructura que crea directamente la plantilla, y sobre ella asumí realmente todo el proceso cuando empecé, sin ponerle mucha cabeza al asunto.

**Comment by cdvv7788** [comment]
Podríamos reemplazarla por django-allauth, mover el modelo de usuario a una nueva app (o usar accounts) y despues tratar de replicar la funcionalidad que pretendías.

**Comment by sebastian-code** [comment]
Es una buena idea, solo seria incluir también el diseño de las plantillas creadas para la presentación de los modelos.
