### ISSUE TITLE
Error NoReverseMatch

### ISSUE THREAD

**Issue by sebastian-code** [sebastian-code/django_cali#17]
Error on login and signup features because error type "NoReverseMatch: u'profiles' is not a registered namespace".

**Comment by cdvv7788** [comment]
There must be a leftover of the profiles app somewhere. I will look it up.

**Comment by cdvv7788** [comment]
In settings:
LOGIN_REDIRECT_URL = reverse_lazy("profiles:show_self")
LOGIN_URL = reverse_lazy("accounts:login")

I think that is not required anymore.

**Comment by sebastian-code** [comment]
I corrected this, as you can see in the most recent commit, the app works until you attemp to login or register, it throws an error because django can't find the redirecting url specified into the app url assignation.

I haven't been able to find the bug, so I gladly accept some help to fix it.

**Comment by cdvv7788** [comment]
If i set LOGIN_REDIRECT_URL explicitly it will work, but i can't find where the profile setting is being defined. I am working on finding that.

**Comment by cdvv7788** [comment]
https://docs.djangoproject.com/en/1.8/ref/settings/#login-redirect-url
I will make it default to the root for now.

**Comment by cdvv7788** [comment]
We can close this one, right?

**Comment by sebastian-code** [comment]
Yes
