### ISSUE TITLE
Adicionar vagrantfile o dockerfile

### ISSUE THREAD

**Issue by cdvv7788** [sebastian-code/django_cali#7]
Usar una de estas alternativas de virtualizacion permite acelerar el proceso de replicacion de instancias.

**Comment by sebastian-code** [comment]
Realmente es algo que no he trabajado porque hasta el momento no es una construcción elaborada, y con un simple uso de virtualenv se solventa; estas construcciones de instancias funcionarían perfectamente para implementar BBDD como PostgreSQL, configurar lo necesario para usar Nginx y Gunicorn (o claro, con otros servidores), lo que además ayuda en el despliegue.

La idea es muy buena ¿porque no te haces un pull request incorporando esas opciones?

**Comment by cdvv7788** [comment]
Eso estaba pensando. En cuanto tenga tiempo lo hare y actualizare el readme para incluir el proceso de instalacion. (perdon por las tildes...teclado rebelde)

**Comment by cdvv7788** [comment]
El ultimo pull request incluía un vagrantfile, aunque aún necesita unas ligeras modificaciones para poder crear una instancia completa de forma automatica. En terminos generales me gustaría tener el proyecto corriendo en postgres (incluso en dev) y tener expuestos los puertos para postgres y django en la maquina virtual. vagrant up debería ser suficiente para tener una instancia completa corriendo.

**Comment by sebastian-code** [comment]
Perfecto, no veo problema para ello y me parece que es una excelente practica. Me toca es aprender a usar Vagrant que nunca lo he usado, nada que no se pueda. Mirando el tema del manager, es curioso, funcionaba antes sin necesidad de declarar el manager en los modelos y sin problema, me toca revisar cada cambio a ver que paso.

**Comment by cdvv7788** [comment]
Lo del manager es principalmente por buenas practicas ( http://stackoverflow.com/questions/7692487/using-django-managers-vs-staticmethod-on-model-class-directly ).
En python3 te va a funcionar sin problemas, aunque no te va a correr en python2.
La idea es que las funciones que realizan modificaciones a nivel de tabla vayan en un manager, así quedan al mismo nivel que otras funciones similares (filter() es un ejemplo). Siguiendo esta convención en la clase solo deberían ir metodos que realizan modificaciones a nivel de objeto (no estaticos).
Si alquien mas va a leer este código, esperaría encontrar esta estructura, la cual separa claramente diferentes niveles de operaciones sobre el model.

**Comment by sebastian-code** [comment]
Creo que con este commit 5a2db56adee2f35ce810be3f0fc228cbc26dacd8 se da por terminado el requerimiento ¿estoy en lo cierto?
