### ISSUE TITLE
Definir alcance del ejercicio

### ISSUE THREAD

**Issue by cdvv7788** [sebastian-code/django_cali#8]
Seria bueno definir el alcance del ejercicio tambien. Se podria pensar por ejemplo en usar el repositorio para el sitio de django-cali y que todos los miembros aporten y aprendan un poco del proceso de desarrollo. Como dices en el readme, empezar de un ejercicio basico (una landing page, blog, registro, etc) e irle agregando funcionalidades que le permitan a la comunidad aprender.

**Comment by sebastian-code** [comment]
Esa es exactamente mi intención, aunque hay algunos intentos de hacer fork sobre el repositorio, hasta ahora no he recibido el primer pull request para analizar e incorporar. Además GitHub da muchas posibilidades de gestionar el proyecto, como incluir funcionalidades que la gente sugiera, desarrollar otras que se defina como intención por parte de la comunidad, algunas las convertí en issues que aun están pendientes. Otras ni las he pensado. Pero no he querido avanzar en solitario, básicamente porque se pierde la idea del ejercicio que pienso yo, debe ser la colaboración y el aprendizaje.
